### ISSUE TITLE
using str_contains which is PHP8 but packagist mentions php: >=7.2

### ISSUE THREAD

**Issue by contactashish13** [LukeTowers/php-donorperfect-api#1]
https://github.com/LukeTowers/php-donorperfect-api/blob/develop/src/DonorPerfect.php#L205

**Comment by LukeTowers** [comment]
Good catch, although I will say I'm using this package inside of a Laravel package which has had str_contains forever, so that's why I didn't catch it. Feel free to submit a PR to swap it out! Are you actually using this package in any of your projects at the moment? Same question to @filmdc

**Comment by contactashish13** [comment]
@LukeTowers yes I am. I have added a workaround (for anyone else needing it) because I'm using PHP 7.2. Great package btw! :+1: 

```
if(!function_exists('str_contains')){
	function str_contains($haystack, $needle){
		return strpos($haystack, $needle) !== false;
	}
}
```

**Comment by LukeTowers** [comment]
Fixed in https://github.com/LukeTowers/php-donorperfect-api/commit/5de13c37fb70008e47db322b6bc3445eeb9b4e84. Thanks for the report @contactashish13! 

May I ask what sort of project you're using it in and how you've been finding it? I've been developing it for a project that has been the bane of my existence for the past year (mostly because I can't get enough time to work on it, but DP's warts definitely don't make it any easier).

Any features that you can think of to make it easier to work with DP?
